### ISSUE TITLE
cURL highlighting issues on 0.7.1

### ISSUE THREAD

**Issue by Devon-White** [cloud-annotations/docusaurus-openapi#273]
I was upgrading the plugin to 0.7.1 to prepare for a V3 upgrade and noticed that the highlighting for cURL examples doesn't seem to work properly anymore.

Older Version:
![image](https://github.com/cloud-annotations/docusaurus-openapi/assets/86693904/4ecc4bbe-ceed-4347-8bc6-42a78cb8bbb1)

https://deploy-preview-261--docusaurus-openapi.netlify.app/petstore/add-a-new-pet-to-the-store

Newer Version:
![image](https://github.com/cloud-annotations/docusaurus-openapi/assets/86693904/d7232ff5-0d84-437e-b7e4-bfe1dc735b97)

https://deploy-preview-261--docusaurus-openapi.netlify.app/petstore/add-a-new-pet-to-the-store

Experiencing the same thing when upgrading this plugin from 0.6.4 to 0.7.1:

Personal docs on 0.6.4:
![image](https://github.com/cloud-annotations/docusaurus-openapi/assets/86693904/893ed14d-c613-4ae7-b366-ad253c382682)

Personal docs on 0.7.1:
![image](https://github.com/cloud-annotations/docusaurus-openapi/assets/86693904/242de6dd-1a4c-428f-9a3f-742ab13bc949)

**Comment by chris48s** [comment]
I think this is caused by the move to prism-react-renderer 2.x.

- In prism-react-renderer 1.x, 'bash' was one of the included syntaxes https://github.com/FormidableLabs/prism-react-renderer/blob/v1.3.5/src/vendor/prism/includeLangs.js
- In prism-react-renderer 2.x, it is not anymore https://github.com/FormidableLabs/prism-react-renderer/blob/prism-react-renderer%402.3.1/packages/generate-prism-languages/index.ts

so `"highlight": "bash"` here

https://github.com/cloud-annotations/docusaurus-openapi/blob/72a01f62192a0fb1d114de056d30267814e38e8d/packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/Curl/index.tsx#L31-L40

no longer works. The other defaults (node, go, python) are still there.

https://github.com/FormidableLabs/prism-react-renderer/issues/22#issuecomment-1610204570 suggests bash can be loaded as an additional plugin but I have not tested this.
